source 'https://github.com/CocoaPods/Specs.git'
# source 'https://cdn.cocoapods.org/'

# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'ExampleProj' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'PrettyViews', :path => '../'

  # Pods for ExampleProj
  pod 'FoundationX', :git => 'https://github.com/Lguanghui/FoundationX.git'
  pod 'LoveUIKit', :git => 'https://github.com/Lguanghui/LoveUIKit.git'

  target 'ExampleProjTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExampleProjUITests' do
    # Pods for testing
  end

end
